---
Name: newsgridembargo
Only:
  classexists: EmbargoExpirySchedulerExtension
---
NewsGridPage:
  extensions:
    - EmbargoExpirySchedulerExtension

---
Name: newsgridfilterable
Only:
  classexists: FilterableArchiveHolderExtension
---
NewsGridHolder:
  extensions:
    - 'FilterableArchiveHolderExtension'
  pagination_control_tab: "Root.Structure"
  #pagination_insert_before: "SubPages"
  managed_object_class: "NewsGridPage"
  managed_object_date_field: "Date"
NewsGridHolder_Controller:
  extensions:
    - FilterableArchiveHolder_ControllerExtension
NewsGridPage:
  extensions:
    - FilterableArchiveItemExtension
